# Generated by Django 5.2.1 on 2025-09-02 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Course Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('preview', models.FileField(blank=True, null=True, upload_to='courses/previews/', verbose_name='Preview Image')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Lesson Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('position', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Position')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='External Video URL')),
                ('video_key', models.CharField(blank=True, db_index=True, max_length=512, null=True, verbose_name="S3/MinIO Video Key (e.g. 'lessons/videos/uuid.mp4')")),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Course')),
            ],
            options={
                'ordering': ['course', 'position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('course', 'position'), name='unique_lesson_position_per_course')],
            },
        ),
    ]
