# Generated by Django 5.2.1 on 2025-09-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_lesson_video_key_remove_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.AddField(
            model_name='lesson',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='Preview Image'),
        ),
    ]
