# Generated by Django 5.2.1 on 2025-09-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discounted price'),
        ),
    ]
