# Generated by Django 5.2.1 on 2025-09-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_published',
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Is Free'),
        ),
    ]
